services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://127.0.0.1:27017/test?authSource=admin&directConnection=true&replicaSet=rs0
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - forge-network
  mongo:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo_volume:/data/db
      - mongo_config:/data/configdb
    networks:
      - forge-network

networks:
  forge-network:
    driver: bridge

volumes:
  mongo_volume:
  mongo_config:
